Algoritmo "Atividade 2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Guilherme Schroder
// Data atual  : 19/07/2022
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval("Guilherme Schroder")
   escreval("Ribeirão Elias  Aurora  89186-000")
   escreva("(47)996972160")

Fimalgoritmo